name: Build
run-name: Midly Annoyed Minions are building the project
on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - closed
jobs:
  run-build:
    runs-on: [ ubuntu-latest ]
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && startswith(github.event.comment.body, '[#')  # Assumes check-in coments all start with [#
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh
