name: Build
run-name: Midly Annoyed Minions are building the project
on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - closed
    branches: [ "main" ]
jobs:
  jobs01:
    runs-on: [ ubuntu-latest ]
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '{t:')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make build.sh executable
        run: chmod +x build.sh
      - name: Run build.sh
        run: ./build.sh
